#!/bin/bash

# Check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# Append to the history file, don't overwrite it
shopt -s histappend

# Don't put duplicate lines or lines starting with space in the history.
export HISTCONTROL=ignoreboth:erasedups

# Increase history and history file size.
export HISTSIZE=100000
export HISTFILESIZE=200000

# Save and reload the history after each command finishes
function _bash_history_sync {
  history -a
  history -c
  history -r
}
export PROMPT_COMMAND=_bash_history_sync

# Make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# Enable history search by using up/down arrow key.
bind '"\e[A": history-search-backward'
bind '"\e[B": history-search-forward'

# Set EDITOR to vim.
export EDITOR=vim

# Help function for importing path to $PATH
function import_path {
  local path=$1
  [ ":$PATH:" != *":$path:"* ] && export PATH=$PATH:$path
}

# Set user home local path.
import_path $HOME/.local/bin

# Set go path.
export GOPATH=$HOME/go
import_path /usr/local/go/bin
import_path $GOPATH/bin

# Set python3 path
export PY_USER_BASE=`python3 -m site --user-base`
export PY_USER_SITE=`python3 -m site --user-site`
import_path $PY_USER_BASE/bin

# Enable powerline.
if [ -f $PY_USER_SITE/powerline/bindings/bash/powerline.sh ]; then
  python3 $PY_USER_BASE/bin/powerline-daemon -q
  export POWERLINE_BASH_CONTINUATION=1
  export POWERLINE_BASH_SELECT=1
  source $PY_USER_SITE/powerline/bindings/bash/powerline.sh
fi
