name: CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04, macos-10.15]
    steps:
    - uses: actions/checkout@v2
    - name: Installation
      run: INSTALL_FONTS=true ./setup.sh
